title: art.tamouse.org
email: tamara@tamouse.org
description: art by tamouse

# Build settings
baseurl: ""
url: ""
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - .sass-cache/
  - Guardfile
  - Gemfile
  - Gemfile.lock
  - README.txt
  - start.sh
  - package.json
